image:
  repository: pratik6958/demo-app
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  name: demo-app
  type: ClusterIP
  port: 5000
  targetPort: 5000

container:
  name: demo-app
  port: 5000

servicemonitor:
  enabled: true
  interval: 5s
  path: /metrics
  labels:
    release: monitoring
